export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const LOGOUT = "LOGOUT";

export const GET_PROFILE = "GET_PROFILE";
export const PROFILE_ERROR = "PROFILE_ERROR";
export const CLEAR_PROFILE = "CLEAR_PROFILE";

export const GET_PENDING_TRANSACTIONS = "GET_PENDING_TRANSACTIONS";
export const PENDING_TRANSACTIONS_ERROR = "PENDING_TRANSACTIONS_ERROR";

export const MINED_BLOCK_SUCCESS = "MINED_BLOCK_SUCCESS";
export const MINED_BLOCK_FAIL = "MINED_BLOCK_FAIL";

export const SEND_TX_SUCCESS = "SEND_TX_SUCCESS";
export const SEND_TX_FAIL = "SEND_TX_FAIL";
